---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webdeploy
  labels:
    app: webapp
  annotations:
    kubernetes.io/change-cause: "Updating to version 1.2"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: webapp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 20%
      maxUnavailable: 20%
  template:
    metadata:
      labels:
        app: webapp
        version: v1.2
    spec:
      containers:
        - image: caddy
          name: webapptest
          readinessProbe:
            httpGet:
              path: /
              port: 80
          ports:
            - containerPort: 80
