---
apiVersion: batch/v1
kind: Job
metadata: 
  name: oneshot-job
  labels:
    type: downloadjob
spec:
  template:
    metadata:
      labels:
        type: downloadjob
    spec:
      containers:
        - name: job
          image: alpine:latest
          command:
            - sleep
            - 20s
      restartPolicy: OnFailure