---
apiVersion: v1
kind: Pod
metadata:
  name: initcontianers-test
spec:
  containers:
    - name: myjenkins
      image: jenkins/jenkins:latest
      ports:
        - containerPort: 8080
  initContainers:
    - name: init-app-service
      image: alpine:3
      command: ["sleep", "20s"]
    - name: init-db-service
      image: alpine:3
      command: ["sleep", "20s"]