---
apiVersion: v1
kind: Pod
metadata:
  name: mysql-test
spec:
  containers:
    - image: mysql:8
      name: mysqldb
      ports:
        - containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: rootroot