---
apiVersion: v1
kind: Pod
metadata:
  name: resource-requests
spec:
  containers:
    - image: jenkins/jenkins:latest
      name: myjenkins
      ports:
        - containerPort: 8080
      resources:
        requests:
          cpu: "250m"
          memory: "250Mi"