---
apiVersion: v1
kind: Pod
metadata:
  name: resource-limits
spec:
  containers:
    - name: myjenkins
      image: jenkins/jenkins:latest
      ports:
        - containerPort: 8080
      resources:
        limits:
          cpu: "1000m"
          memory: "1000Mi"